# Generated by Django 5.2.15 on 2026-06-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_remove_bug_assignee_bug_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='environment',
            field=models.CharField(blank=True, choices=[('staging', 'Staging'), ('uat', 'UAT'), ('production', 'Production')], max_length=50),
        ),
    ]
