# Generated by Django 5.2.14 on 2026-06-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='can_create_bugs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='can_create_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='can_edit_bugs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='can_edit_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
