# Generated by Django 5.2.14 on 2026-06-09 10:19

import django.db.models.deletion
from django.db import migrations, models


def seed_and_migrate_rbac(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    Role = apps.get_model("accounts", "Role")
    User = apps.get_model("accounts", "User")
    Department = apps.get_model("accounts", "Department")

    from apps.accounts.permission_registry import PERMISSION_REGISTRY, SYSTEM_ROLES

    permissions = {}
    for item in PERMISSION_REGISTRY:
        perm, _ = Permission.objects.update_or_create(
            codename=item["codename"],
            defaults={
                "name": item["name"],
                "category": item["category"],
                "description": item.get("description", ""),
            },
        )
        permissions[perm.codename] = perm

    roles = {}
    for spec in SYSTEM_ROLES:
        role, _ = Role.objects.update_or_create(
            slug=spec["slug"],
            defaults={
                "name": spec["name"],
                "description": spec.get("description", ""),
                "is_system": spec.get("is_system", False),
                "is_admin": spec.get("is_admin", False),
            },
        )
        if not role.is_admin:
            role.permissions.set(
                [permissions[c] for c in spec.get("permissions", []) if c in permissions]
            )
        roles[role.slug] = role

    dept_field_map = {
        "can_create_tasks": "can_create_tasks",
        "can_create_bugs": "can_create_bugs",
        "can_edit_tasks": "can_edit_tasks",
        "can_edit_bugs": "can_edit_bugs",
    }

    for department in Department.objects.all():
        for field, codename in dept_field_map.items():
            if getattr(department, field, False) and codename in permissions:
                department.extra_permissions.add(permissions[codename])

    default_role = roles.get("developer")
    for user in User.objects.all():
        slug = getattr(user, "role", "developer") or "developer"
        user.access_role = roles.get(slug, default_role)
        user.save(update_fields=["access_role"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("category", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="accounts.permission"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="extra_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional permissions granted to all department members.",
                related_name="departments",
                to="accounts.permission",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="access_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.role",
            ),
        ),
        migrations.RunPython(seed_and_migrate_rbac, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="department",
            name="can_create_bugs",
        ),
        migrations.RemoveField(
            model_name="department",
            name="can_create_tasks",
        ),
        migrations.RemoveField(
            model_name="department",
            name="can_edit_bugs",
        ),
        migrations.RemoveField(
            model_name="department",
            name="can_edit_tasks",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
