# Generated by Django 5.2.14 on 2026-06-09 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_feature_sprint'),
        ('tasks', '0002_remove_task_assignee_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.feature'),
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.sprint'),
        ),
    ]
