# Generated by Django 5.2.14 on 2026-06-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_testcase'),
        ('tasks', '0003_task_feature_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tasks', to='projects.testcase'),
        ),
    ]
